name: Build and Push Docker Image

on:
  push:
    branches:
      - mainbranch
  pull_request:
    branches:
      - mainbranch

jobs:
  docker:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pip install flake8

      - name: Build backend Docker image
        run: | 
          docker build -t NUS-ISS-Architecting-AI-Systems-Practice-Project ./backend    
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Build frontend Docker image
        run: | 
          docker build -t NUS-ISS-Architecting-AI-Systems-Practice-Project ./frontend    
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run Flake8
        run: flake8 .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/hawker-app:latest .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/hawker-app:latest
          format: table
          output: trivy-report.txt
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hawker-app:latest

# deploy:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to Ubuntu VM
#         uses: appleboy/ssh-action@v1.2.0
#         with:
#           host: ${{ secrets.VM_HOST }}
#           username: ${{ secrets.VM_USERNAME }}
#           key: ${{ secrets.VM_SSH_KEY }}
#           script: |
#             docker pull ${{ secrets.DOCKER_USERNAME }}/hawker-app:latest

#             docker stop hawker-app || true
#             docker rm hawker-app || true

#             docker run -d \
#               --name hawker-app \
#               --restart unless-stopped \
#               -p 80:5000 \
#               ${{ secrets.DOCKER_USERNAME }}/hawker-app:latest

#remember to install docker on the ubuntu vm before running deploy 
# sudo apt update
# sudo apt install docker.io -y
# sudo systemctl enable docker
# sudo systemctl start docker
