name: Build and Push Docker Image

on:
  push:
    branches:
      - mainbranch
  pull_request:
    branches:
      - mainbranch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hawker-app:latest

# deploy:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to Ubuntu VM
#         uses: appleboy/ssh-action@v1.2.0
#         with:
#           host: ${{ secrets.VM_HOST }}
#           username: ${{ secrets.VM_USERNAME }}
#           key: ${{ secrets.VM_SSH_KEY }}
#           script: |
#             docker pull ${{ secrets.DOCKER_USERNAME }}/hawker-app:latest

#             docker stop hawker-app || true
#             docker rm hawker-app || true

#             docker run -d \
#               --name hawker-app \
#               --restart unless-stopped \
#               -p 80:5000 \
#               ${{ secrets.DOCKER_USERNAME }}/hawker-app:latest

#remember to install docker on the ubuntu vm before running deploy 
# sudo apt update
# sudo apt install docker.io -y
# sudo systemctl enable docker
# sudo systemctl start docker
